(function(){
var c=document.getElementById('light-rays-bg');if(!c||typeof OGL==='undefined')return;
var R=OGL,config={raysOrigin:'top-center',raysColor:'#7DD4D0',raysSpeed:1.2,lightSpread:0.8,rayLength:1.5,pulsating:false,fadeDistance:1.0,saturation:0.8,followMouse:true,mouseInfluence:0.15,noiseAmount:0.05,distortion:0.03};
var renderer,uniforms,mesh,animId,mouseX=0.5,mouseY=0.5,smoothX=0.5,smoothY=0.5;
function h2r(h){var m=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(h);return m?[parseInt(m[1],16)/255,parseInt(m[2],16)/255,parseInt(m[3],16)/255]:[1,1,1]}
function gA(o,w,h){var u=0.2;switch(o){case'top-left':return{anchor:[0,-u*h],dir:[0,1]};case'top-right':return{anchor:[w,-u*h],dir:[0,1]};case'left':return{anchor:[-u*w,.5*h],dir:[1,0]};case'right':return{anchor:[(1+u)*w,.5*h],dir:[-1,0]};case'bottom-left':return{anchor:[0,(1+u)*h],dir:[0,-1]};case'bottom-center':return{anchor:[.5*w,(1+u)*h],dir:[0,-1]};case'bottom-right':return{anchor:[w,(1+u)*h],dir:[0,-1]};default:return{anchor:[.5*w,-u*h],dir:[0,1]}}}
function init(){
renderer=new R.Renderer({dpr:Math.min(window.devicePixelRatio,2),alpha:true});
var gl=renderer.gl;gl.canvas.style.cssText='width:100%;height:100%;display:block;';c.appendChild(gl.canvas);
var vert='attribute vec2 position;varying vec2 vUv;void main(){vUv=position*0.5+0.5;gl_Position=vec4(position,0.0,1.0);}';
var frag='precision highp float;uniform float iTime;uniform vec2 iResolution;uniform vec2 rayPos;uniform vec2 rayDir;uniform vec3 raysColor;uniform float raysSpeed;uniform float lightSpread;uniform float rayLength;uniform float pulsating;uniform float fadeDistance;uniform float saturation;uniform vec2 mousePos;uniform float mouseInfluence;uniform float noiseAmount;uniform float distortion;varying vec2 vUv;float n(vec2 s){return fract(sin(dot(s.xy,vec2(12.9898,78.233)))*43758.5453123);}float rS(vec2 rs,vec2 rd,vec2 c,float a,float b,float sp){vec2 s=c-rs;vec2 dn=normalize(s);float ca=dot(dn,rd);float da=ca+distortion*sin(iTime*2.0+length(s)*0.01)*0.2;float sf=pow(max(da,0.0),1.0/max(lightSpread,0.001));float d=length(s);float md=iResolution.x*rayLength;float lf=clamp((md-d)/md,0.0,1.0);float ff=clamp((iResolution.x*fadeDistance-d)/(iResolution.x*fadeDistance),0.5,1.0);float pu=pulsating>0.5?(0.8+0.2*sin(iTime*sp*3.0)):1.0;float bs=clamp((0.45+0.15*sin(da*a+iTime*sp))+(0.3+0.2*cos(-da*b+iTime*sp)),0.0,1.0);return bs*lf*ff*sf*pu;}void mI(out vec4 o,in vec2 fc){vec2 coord=vec2(fc.x,iResolution.y-fc.y);vec2 frd=rayDir;if(mouseInfluence>0.0){vec2 msp=mousePos*iResolution.xy;vec2 md=normalize(msp-rayPos);frd=normalize(mix(rayDir,md,mouseInfluence));}vec4 r1=vec4(1.0)*rS(rayPos,frd,coord,36.2214,21.11349,1.5*raysSpeed);vec4 r2=vec4(1.0)*rS(rayPos,frd,coord,22.3991,18.0234,1.1*raysSpeed);o=r1*0.5+r2*0.4;if(noiseAmount>0.0){float no=n(coord*0.01+iTime*0.1);o.rgb*=(1.0-noiseAmount+noiseAmount*no);}float br=1.0-(coord.y/iResolution.y);o.x*=0.1+br*0.8;o.y*=0.3+br*0.6;o.z*=0.5+br*0.5;if(saturation!=1.0){float gr=dot(o.rgb,vec3(0.299,0.587,0.114));o.rgb=mix(vec3(gr),o.rgb,saturation);}o.rgb*=raysColor;}void main(){vec4 color;mI(color,gl_FragCoord.xy);gl_FragColor=color;}';
uniforms={iTime:{value:0},iResolution:{value:[1,1]},rayPos:{value:[0,0]},rayDir:{value:[0,1]},raysColor:{value:h2r(config.raysColor)},raysSpeed:{value:config.raysSpeed},lightSpread:{value:config.lightSpread},rayLength:{value:config.rayLength},pulsating:{value:config.pulsating?1:0},fadeDistance:{value:config.fadeDistance},saturation:{value:config.saturation},mousePos:{value:[0.5,0.5]},mouseInfluence:{value:config.mouseInfluence},noiseAmount:{value:config.noiseAmount},distortion:{value:config.distortion}};
var geo=new R.Triangle(gl);var prog=new R.Program(gl,{vertex:vert,fragment:frag,uniforms:uniforms});mesh=new R.Mesh(gl,{geometry:geo,program:prog});
function resize(){renderer.dpr=Math.min(window.devicePixelRatio,2);var w=c.clientWidth,h=c.clientHeight;renderer.setSize(w,h);var dpr=renderer.dpr,w2=w*dpr,h2=h*dpr;uniforms.iResolution.value=[w2,h2];var p=gA(config.raysOrigin,w2,h2);uniforms.rayPos.value=p.anchor;uniforms.rayDir.value=p.dir;}
function loop(t){if(!uniforms)return;uniforms.iTime.value=t*0.001;if(config.followMouse&&config.mouseInfluence>0){var sm=0.92;smoothX=smoothX*sm+mouseX*(1-sm);smoothY=smoothY*sm+mouseY*(1-sm);uniforms.mousePos.value=[smoothX,smoothY];}try{renderer.render({scene:mesh});animId=requestAnimationFrame(loop);}catch(e){}}
window.addEventListener('resize',resize);resize();animId=requestAnimationFrame(loop);
}
function onM(e){var r=c.getBoundingClientRect();mouseX=(e.clientX-r.left)/r.width;mouseY=(e.clientY-r.top)/r.height;}
document.addEventListener('mousemove',onM);init();
})();
