import{Renderer,Program,Mesh,Triangle}from'https://cdn.jsdelivr.net/npm/ogl@0.0.29/+esm';
var c=document.getElementById('aurora-bg');if(!c)return;
var cfg={speed:0.5,scale:1.2,brightness:0.8,color1:'#7DD4D0',color2:'#5ABFBA',noiseFrequency:2.0,noiseAmplitude:1.0,bandHeight:0.5,bandSpread:1.0,octaveDecay:0.1,layerOffset:0,colorSpeed:1.0,enableMouse:true,mouseInfluence:0.25};
function h2v(h){var m=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(h);return m?[parseInt(m[1],16)/255,parseInt(m[2],16)/255,parseInt(m[3],16)/255]:[1,1,1]}
var renderer=new Renderer({alpha:true,premultipliedAlpha:false});
var gl=renderer.gl;gl.clearColor(0,0,0,0);
var geo=new Triangle(gl);
var vert='attribute vec2 uv;attribute vec2 position;varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position,0,1);}';
var frag='precision highp float;uniform float uTime;uniform vec3 uResolution;uniform float uSpeed;uniform float uScale;uniform float uBrightness;uniform vec3 uColor1;uniform vec3 uColor2;uniform float uNoiseFreq;uniform float uNoiseAmp;uniform float uBandHeight;uniform float uBandSpread;uniform float uOctaveDecay;uniform float uLayerOffset;uniform float uColorSpeed;uniform vec2 uMouse;uniform float uMouseInfluence;uniform bool uEnableMouse;varying vec2 vUv;vec3 gH(vec3 p){p=vec3(dot(p,vec3(127.1,311.7,234.6)),dot(p,vec3(269.5,183.3,198.3)),dot(p,vec3(169.5,283.3,156.9)));vec3 h=fract(sin(p)*43758.5453123);float phi=acos(2.0*h.x-1.0);float theta=6.28318*h.y;return vec3(cos(theta)*sin(phi),sin(theta)*cos(phi),cos(phi));}float qS(float t){float t2=t*t,t3=t*t2;return 6.0*t3*t2-15.0*t2*t2+10.0*t3;}vec3 cG(float t,vec3 a,vec3 b,vec3 c,vec3 d){return a+b*cos(6.28318*(c*t+d));}float p3D(float a,float f,float px,float py,float pz){float x=px*f,y=py*f;float fx=floor(x),fy=floor(y),fz=floor(pz),cx=ceil(x),cy=ceil(y),cz=ceil(pz);vec3 g000=gH(vec3(fx,fy,fz)),g100=gH(vec3(cx,fy,fz)),g010=gH(vec3(fx,cy,fz)),g110=gH(vec3(cx,cy,fz)),g001=gH(vec3(fx,fy,cz)),g101=gH(vec3(cx,fy,cz)),g011=gH(vec3(fx,cy,cz)),g111=gH(vec3(cx,cy,cz));float d000=dot(g000,vec3(x-fx,y-fy,pz-fz)),d100=dot(g100,vec3(x-cx,y-fy,pz-fz)),d010=dot(g010,vec3(x-fx,y-cy,pz-fz)),d110=dot(g110,vec3(x-cx,y-cy,pz-fz)),d001=dot(g001,vec3(x-fx,y-fy,pz-cz)),d101=dot(g101,vec3(x-cx,y-fy,pz-cz)),d011=dot(g011,vec3(x-fx,y-cy,pz-cz)),d111=dot(g111,vec3(x-cx,y-cy,pz-cz));float sx=qS(x-fx),sy=qS(y-fy),sz=qS(pz-fz);return a*mix(mix(mix(d000,d100,sx),mix(d010,d110,sx),sy),mix(mix(d001,d101,sx),mix(d011,d111,sx),sy),sz);}float aG(float t,vec2 sh){vec2 uv2=gl_FragCoord.xy/uResolution.y+sh;float nv=0.0,f=uNoiseFreq,a=uNoiseAmp;vec2 sp=uv2*uScale;for(float i=0.0;i<3.0;i+=1.0){nv+=p3D(a,f,sp.x,sp.y,t);a*=uOctaveDecay;f*=2.0;}float yB=uv2.y*10.0-uBandHeight*10.0;return 0.3*max(exp(uBandSpread*(1.0-1.1*abs(nv+yB))),0.0);}void main(){vec2 uv=gl_FragCoord.xy/uResolution.xy;float t=uSpeed*0.4*uTime;vec2 sh=vec2(0.0);if(uEnableMouse)sh=(uMouse-0.5)*uMouseInfluence;vec3 col=vec3(0.0);col+=0.99*aG(t,sh)*cG(uv.x+uTime*uSpeed*0.2*uColorSpeed,vec3(0.5),vec3(0.5),vec3(1.0),vec3(0.3,0.20,0.20))*uColor1;col+=0.99*aG(t+uLayerOffset,sh)*cG(uv.x+uTime*uSpeed*0.1*uColorSpeed,vec3(0.5),vec3(0.5),vec3(2.0,1.0,0.0),vec3(0.5,0.20,0.25))*uColor2;col*=uBrightness;gl_FragColor=vec4(col,clamp(length(col),0.0,1.0));}';
var unis={uTime:{value:0},uResolution:{value:[gl.canvas.width,gl.canvas.height,gl.canvas.width/gl.canvas.height]},uSpeed:{value:cfg.speed},uScale:{value:cfg.scale},uBrightness:{value:cfg.brightness},uColor1:{value:h2v(cfg.color1)},uColor2:{value:h2v(cfg.color2)},uNoiseFreq:{value:cfg.noiseFrequency},uNoiseAmp:{value:cfg.noiseAmplitude},uBandHeight:{value:cfg.bandHeight},uBandSpread:{value:cfg.bandSpread},uOctaveDecay:{value:cfg.octaveDecay},uLayerOffset:{value:cfg.layerOffset},uColorSpeed:{value:cfg.colorSpeed},uMouse:{value:[0.5,0.5]},uMouseInfluence:{value:cfg.mouseInfluence},uEnableMouse:{value:cfg.enableMouse}};
var prog=new Program(gl,{vertex:vert,fragment:frag,uniforms:unis});
var mesh=new Mesh(gl,{geometry:geo,program:prog});
c.appendChild(gl.canvas);
var cm=[0.5,0.5],tm=[0.5,0.5];
function mm(e){var r=gl.canvas.getBoundingClientRect();tm[0]=(e.clientX-r.left)/r.width;tm[1]=1.0-(e.clientY-r.top)/r.height;}
function ml(){tm=[0.5,0.5];}
if(cfg.enableMouse){gl.canvas.addEventListener('mousemove',mm);gl.canvas.addEventListener('mouseleave',ml);}
function resize(){renderer.setSize(c.offsetWidth,c.offsetHeight);if(prog)prog.uniforms.uResolution.value=[gl.canvas.width,gl.canvas.height,gl.canvas.width/gl.canvas.height];}
window.addEventListener('resize',resize);resize();
(function loop(t){prog.uniforms.uTime.value=t*0.001;if(cfg.enableMouse){cm[0]+=0.05*(tm[0]-cm[0]);cm[1]+=0.05*(tm[1]-cm[1]);prog.uniforms.uMouse.value[0]=cm[0];prog.uniforms.uMouse.value[1]=cm[1];}
renderer.render({scene:mesh});requestAnimationFrame(loop);})(0);
